### ISSUE TITLE
ARM64 Docker image feature

### ISSUE THREAD

**Issue by nlamirault** [fjogeleit/policy-reporter-ui#2]
It would be really good to have an arm64 compatible Docker image to deploy the application on a Kubernetes Raspberry PI cluster

**Comment by fjogeleit** [comment]
I created a new image version with ARM64 Support. After I created a new version for each component I will provide a new Chart Version

https://hub.docker.com/layers/fjogeleit/policy-reporter-ui/0.11.0/images/sha256-f46737d27146033918deef9c463cea9c34c0f9fb7b84f4feab0144a95875f00d?context=repo
